// ============================================================
// Phase 5C-B.3 — Coffee Natural Language UI & Integration Tests
//
// Verifies:
//   1. Coffee AI entry & description submission
//   2. AI extraction workflow with mock provider
//   3. Extracted fields and evidence display
//   4. Field status badges & dynamic requirements (getRequiredCoffeeInformation)
//   5. User attribute editing without re-invoking Gemini (roasting, decaf, presentation, form, grade)
//   6. Unknown attribute handling (explicit display, not auto-guessed)
//   7. Ambiguity handling and user candidate resolution (form, grade)
//   8. Confirmation validation (blocks when insufficient info, proceeds when complete)
//   9. Invariant: HS code is ALWAYS generated by classifyCoffee(), NEVER by Gemini
//   10. Security: Prompt injection and malicious HS codes in extraction are neutralized
//   11. Result states: Classified (0901 21 10, etc.), Insufficient Information, No Match
//   12. UX: Back navigation, Start Again, Manual fallback, API error recovery, Retry
//   13. Deterministic Invariant Test: Roasted Arabica plantation Grade A bulk -> 0901 21 10
// ============================================================

import { describe, it, expect } from "vitest"
import {
  extractCoffeeDescription,
  type CoffeeExtractionProvider,
  type CoffeeProviderExtractionPayload,
} from "@/products/coffee/ai/extractor"
import { toCoffeeClassificationInput } from "@/products/coffee/ai/toCoffeeClassificationInput"
import {
  classifyCoffee,
  getRequiredCoffeeInformation,
} from "@/products/coffee/index"
import type { CoffeeExtraction } from "@/products/coffee/ai/types"
import type { CoffeeClassificationInput } from "@/products/coffee/types"

/**
 * Creates a mock Coffee extraction provider that tracks call count.
 */
function createMockCoffeeProvider(
  payload: CoffeeProviderExtractionPayload
): CoffeeExtractionProvider & { readonly callCount: number } {
  let callCount = 0
  return {
    name: "MockCoffeeProvider",
    get callCount() {
      return callCount
    },
    async extract(_text: string) {
      callCount++
      return payload
    },
  }
}

describe("Phase 5C-B.3 — Coffee AI Workflow & Review Integration", () => {
  // ── 1. Basic Workflow ───────────────────────────────────────

  it("1-6. Basic Workflow: Submits description, extracts attributes, verifies evidence and fields", async () => {
    const sourceText =
      "Roasted Arabica plantation coffee, Grade A, non-decaffeinated, bulk packaging."
    const mockPayload: CoffeeProviderExtractionPayload = {
      attributes: {
        productCategory: "coffee",
        productType: "coffee",
        roasted: true,
        decaffeinated: false,
        presentation: "bulk",
        form: "arabica_plantation",
        grade: "A",
      },
      evidence: [
        { field: "roasted", sourceText: "Roasted" },
        { field: "form", sourceText: "Arabica plantation" },
        { field: "grade", sourceText: "Grade A" },
        { field: "decaffeinated", sourceText: "non-decaffeinated" },
        { field: "presentation", sourceText: "bulk packaging" },
      ],
      ambiguities: [],
    }

    const mockProvider = createMockCoffeeProvider(mockPayload)
    const extractionResult = await extractCoffeeDescription(sourceText, {
      provider: mockProvider,
    })

    // 1. Extraction returned
    expect(extractionResult.status).toBe("extracted")
    expect(mockProvider.callCount).toBe(1)

    // 2. Extracted fields displayed correctly
    expect(extractionResult.attributes.productCategory).toBe("coffee")
    expect(extractionResult.attributes.productType).toBe("coffee")
    expect(extractionResult.attributes.roasted).toBe(true)
    expect(extractionResult.attributes.decaffeinated).toBe(false)
    expect(extractionResult.attributes.presentation).toBe("bulk")
    expect(extractionResult.attributes.form).toBe("arabica_plantation")
    expect(extractionResult.attributes.grade).toBe("A")

    // 3. Evidence displayed
    expect(extractionResult.evidence.length).toBe(5)
    const roastedEv = extractionResult.evidence.find((e) => e.field === "roasted")
    expect(roastedEv?.sourceText).toBe("Roasted")
    const formEv = extractionResult.evidence.find((e) => e.field === "form")
    expect(formEv?.sourceText).toBe("Arabica plantation")
  })

  // ── 2. Editing Attributes Without Re-invoking Gemini ─────────

  it("7-12. Editing: Editing roasting, decaf, presentation, form, grade does NOT re-call Gemini", async () => {
    const mockPayload: CoffeeProviderExtractionPayload = {
      attributes: {
        productCategory: "coffee",
        productType: "coffee",
        roasted: true,
        decaffeinated: "unknown",
        presentation: "bulk",
        form: "unknown",
        grade: "unknown",
      },
      evidence: [
        { field: "roasted", sourceText: "Roasted" },
        { field: "presentation", sourceText: "bulk" },
      ],
      ambiguities: [],
    }

    const mockProvider = createMockCoffeeProvider(mockPayload)
    const extractionResult = await extractCoffeeDescription("Roasted bulk coffee", {
      provider: mockProvider,
    })
    expect(mockProvider.callCount).toBe(1)

    // User edits roasting: true -> false
    let editedState: CoffeeExtraction = {
      ...extractionResult.attributes,
      roasted: false,
    }
    expect(mockProvider.callCount).toBe(1) // Still 1

    // User edits decaffeination: "unknown" -> false
    editedState = {
      ...editedState,
      decaffeinated: false,
    }
    expect(mockProvider.callCount).toBe(1) // Still 1

    // User edits presentation: "bulk" -> "other"
    editedState = {
      ...editedState,
      presentation: "other",
    }
    expect(mockProvider.callCount).toBe(1) // Still 1

    // User edits form: "unknown" -> "arabica_plantation"
    editedState = {
      ...editedState,
      form: "arabica_plantation",
    }
    expect(mockProvider.callCount).toBe(1) // Still 1

    // User edits grade: "unknown" -> "B"
    editedState = {
      ...editedState,
      grade: "B",
    }
    expect(mockProvider.callCount).toBe(1) // Still 1

    // Convert edited attributes to classification input and classify
    const conversion = toCoffeeClassificationInput(editedState)
    expect(conversion.success).toBe(true)
    if (!conversion.success) return

    const result = classifyCoffee(conversion.input)
    expect(result.status).toBe("classified")
    if (result.status === "classified") {
      expect(result.hsCode).toBe("09011112")
    }

    // Verify Gemini was NEVER called during the edit operations
    expect(mockProvider.callCount).toBe(1)
  })

  // ── 3. Unknown Values & Required Information Checks ─────────

  it("13. Missing roasting: Requires roasting status before classification", () => {
    const partial: Partial<CoffeeClassificationInput> = {
      productCategory: "coffee",
      productType: "coffee",
      roasted: undefined,
      decaffeinated: false,
      presentation: "bulk",
    }

    const reqInfo = getRequiredCoffeeInformation(partial)
    expect(reqInfo.sufficient).toBe(false)
    expect(reqInfo.fieldStatus.roasted).toBe("required")
    expect(reqInfo.missingFields).toContain("roasted")
    expect(reqInfo.reason).toMatch(/roasting/i)
  })

  it("14. Missing decaffeination on roasted coffee: Requires decaffeination", () => {
    const partial: Partial<CoffeeClassificationInput> = {
      productCategory: "coffee",
      productType: "coffee",
      roasted: true,
      decaffeinated: undefined,
      presentation: "bulk",
    }

    const reqInfo = getRequiredCoffeeInformation(partial)
    expect(reqInfo.sufficient).toBe(false)
    expect(reqInfo.fieldStatus.decaffeinated).toBe("required")
    expect(reqInfo.missingFields).toContain("decaffeinated")
  })

  it("15. Missing presentation on roasted coffee: Requires presentation (bulk vs other)", () => {
    const partial: Partial<CoffeeClassificationInput> = {
      productCategory: "coffee",
      productType: "coffee",
      roasted: true,
      decaffeinated: false,
      presentation: undefined,
    }

    const reqInfo = getRequiredCoffeeInformation(partial)
    expect(reqInfo.sufficient).toBe(false)
    expect(reqInfo.fieldStatus.presentation).toBe("required")
    expect(reqInfo.missingFields).toContain("presentation")
  })

  it("16. Missing form on unroasted non-decaf: Requires form / variety", () => {
    const partial: Partial<CoffeeClassificationInput> = {
      productCategory: "coffee",
      productType: "coffee",
      roasted: false,
      decaffeinated: false,
      form: undefined,
    }

    const reqInfo = getRequiredCoffeeInformation(partial)
    expect(reqInfo.sufficient).toBe(false)
    expect(reqInfo.fieldStatus.form).toBe("required")
    expect(reqInfo.missingFields).toContain("form")
  })

  it("17. Missing grade on Arabica plantation: Requires grade", () => {
    const partial: Partial<CoffeeClassificationInput> = {
      productCategory: "coffee",
      productType: "coffee",
      roasted: false,
      decaffeinated: false,
      form: "arabica_plantation",
      grade: undefined,
    }

    const reqInfo = getRequiredCoffeeInformation(partial)
    expect(reqInfo.sufficient).toBe(false)
    expect(reqInfo.fieldStatus.grade).toBe("required")
    expect(reqInfo.missingFields).toContain("grade")
  })

  // ── 4. Ambiguity Resolution ────────────────────────────────

  it("18-20. Ambiguity: Handles ambiguous form & grade; user resolves ambiguity", async () => {
    const mockPayload: CoffeeProviderExtractionPayload = {
      attributes: {
        productCategory: "coffee",
        productType: "coffee",
        roasted: false,
        decaffeinated: false,
        presentation: "bulk",
        form: "unknown",
        grade: "unknown",
      },
      evidence: [],
      ambiguities: [
        {
          field: "form",
          candidates: ["arabica_cherry", "rob_cherry"],
          reason: "Description mentions cherry coffee without specifying Arabica or Robusta.",
        },
        {
          field: "grade",
          candidates: ["AB", "PB"],
          reason: "Description references mixed Grade AB/PB lots.",
        },
      ],
    }

    const mockProvider = createMockCoffeeProvider(mockPayload)
    const extractionResult = await extractCoffeeDescription(
      "Cherry coffee beans Grade AB or PB",
      { provider: mockProvider }
    )

    expect(extractionResult.status).toBe("needs_clarification")
    expect(extractionResult.ambiguities.length).toBe(2)
    expect(extractionResult.ambiguities[0].candidates).toEqual([
      "arabica_cherry",
      "rob_cherry",
    ])
    expect(extractionResult.ambiguities[1].candidates).toEqual(["AB", "PB"])

    // Prior to resolution, requirements engine blocks confirmation
    const conversionBefore = toCoffeeClassificationInput(extractionResult.attributes)
    expect(conversionBefore.success).toBe(true)
    if (conversionBefore.success) {
      const check = getRequiredCoffeeInformation(conversionBefore.input)
      expect(check.sufficient).toBe(false)
      expect(check.missingFields).toContain("form")
    }

    // User resolves ambiguity to "arabica_cherry" and grade "AB"
    const resolvedState: CoffeeExtraction = {
      ...extractionResult.attributes,
      form: "arabica_cherry",
      grade: "AB",
    }

    const conversionAfter = toCoffeeClassificationInput(resolvedState)
    expect(conversionAfter.success).toBe(true)
    if (!conversionAfter.success) return

    const checkAfter = getRequiredCoffeeInformation(conversionAfter.input)
    expect(checkAfter.sufficient).toBe(true)

    // Run classification
    const result = classifyCoffee(conversionAfter.input)
    expect(result.status).toBe("classified")
    if (result.status === "classified") {
      expect(result.hsCode).toBe("09011121")
    }
  })

  // ── 5. Confirmation & Requirements Validation ──────────────

  it("21-24. Confirmation: Validates requirements before calling classifyCoffee()", () => {
    // Insufficient input (missing roasted)
    const incompleteExtraction: CoffeeExtraction = {
      productCategory: "coffee",
      productType: "coffee",
      roasted: "unknown",
      decaffeinated: "unknown",
      presentation: "unknown",
      form: "unknown",
      grade: "unknown",
    }

    const conv1 = toCoffeeClassificationInput(incompleteExtraction)
    expect(conv1.success).toBe(true)
    if (conv1.success) {
      const check = getRequiredCoffeeInformation(conv1.input)
      expect(check.sufficient).toBe(false)
      expect(check.missingFields).toContain("roasted")
    }

    // Sufficient input (roasted, decaf, bulk)
    const completeExtraction: CoffeeExtraction = {
      productCategory: "coffee",
      productType: "coffee",
      roasted: true,
      decaffeinated: true,
      presentation: "bulk",
      form: "unknown",
      grade: "unknown",
    }

    const conv2 = toCoffeeClassificationInput(completeExtraction)
    expect(conv2.success).toBe(true)
    if (!conv2.success) return

    const check2 = getRequiredCoffeeInformation(conv2.input)
    expect(check2.sufficient).toBe(true)

    // classifyCoffee is called only after sufficient info
    const classificationResult = classifyCoffee(conv2.input)
    expect(classificationResult.status).toBe("classified")
    if (classificationResult.status === "classified") {
      expect(classificationResult.hsCode).toBe("09012210")
    }
  })

  // ── 6. Security & Invariant Enforcement ────────────────────

  it("25-27. Security: Injected HS codes or classification fields in Gemini payload are rejected", async () => {
    // Attempted injection of HS code into attributes
    const maliciousPayload = {
      attributes: {
        productCategory: "coffee",
        productType: "coffee",
        roasted: true,
        decaffeinated: false,
        presentation: "bulk",
        form: "unknown",
        grade: "unknown",
        hsCode: "09012110", // FORBIDDEN FIELD
      } as unknown as CoffeeExtraction,
      evidence: [],
      ambiguities: [],
    }

    const mockProvider = createMockCoffeeProvider(maliciousPayload)
    const result = await extractCoffeeDescription("Roasted bulk coffee", {
      provider: mockProvider,
    })

    // Validation catches forbidden keys and returns error status
    expect(result.status).toBe("error")
    expect(result.errorCode).toBe("INVALID_AI_RESPONSE")
    expect(result.errorMessage).toMatch(/forbidden/i)
  })

  // ── 7. Result Types ────────────────────────────────────────

  it("28. Result: Successfully classifies coffee husks & skins -> 0901 90 10", () => {
    const input: CoffeeClassificationInput = {
      productCategory: "coffee",
      productType: "husks_and_skins",
    }

    const req = getRequiredCoffeeInformation(input)
    expect(req.sufficient).toBe(true)

    const result = classifyCoffee(input)
    expect(result.status).toBe("classified")
    if (result.status === "classified") {
      expect(result.hsCode).toBe("09019010")
      expect(result.matchedRuleId).toBe("COF-022")
    }
  })

  it("29. Result: No-match result for undefined/clarification lines", () => {
    const input: CoffeeClassificationInput = {
      productCategory: "coffee",
      productType: "coffee",
      roasted: false,
      decaffeinated: false,
      form: "other",
    }

    const result = classifyCoffee(input)
    expect(result.status).toBe("no_match")
    if (result.status === "no_match") {
      expect(result.message).toMatch(/clarification/i)
    }
  })

  it("30. Result: Insufficient information result when required fields are missing", () => {
    const input: CoffeeClassificationInput = {
      productCategory: "coffee",
      productType: "coffee",
      roasted: true,
      decaffeinated: undefined,
      presentation: undefined,
    }

    const result = classifyCoffee(input)
    expect(result.status).toBe("insufficient_information")
    if (result.status === "insufficient_information") {
      expect(result.missingFields).toContain("decaffeinated")
      expect(result.missingFields).toContain("presentation")
    }
  })

  // ── 8. Non-Coffee Input Rejection ──────────────────────────

  it("31-35. Non-Coffee Input: Returns unsupported status with clear message", async () => {
    const mockPayload: CoffeeProviderExtractionPayload = {
      attributes: {
        productCategory: "unknown",
        productType: "unknown",
        roasted: "unknown",
        decaffeinated: "unknown",
        presentation: "unknown",
        form: "unknown",
        grade: "unknown",
      },
      evidence: [],
      ambiguities: [],
      notes: "This product appears to be automotive engine oil, not coffee.",
    }

    const mockProvider = createMockCoffeeProvider(mockPayload)
    const result = await extractCoffeeDescription("Synthetic 5W-30 engine oil", {
      provider: mockProvider,
    })

    expect(result.status).toBe("unsupported")
    expect(result.errorCode).toBe("UNSUPPORTED_PRODUCT")
    expect(result.notes).toContain("automotive engine oil")

    // Conversion fails
    const conversion = toCoffeeClassificationInput(result.attributes)
    expect(conversion.success).toBe(false)
  })

  // ── 9. Critical Deterministic Invariant Test (Section 25) ───

  it("25. Critical Deterministic Invariant Test: 'Roasted Arabica plantation coffee, Grade A, non-decaffeinated, bulk.' -> 0901 21 10 via classifyCoffee()", async () => {
    const sourceText =
      "Roasted Arabica plantation coffee, Grade A, non-decaffeinated, bulk."

    // 1. Gemini extracts facts ONLY
    const mockGeminiPayload: CoffeeProviderExtractionPayload = {
      attributes: {
        productCategory: "coffee",
        productType: "coffee",
        roasted: true,
        decaffeinated: false,
        presentation: "bulk",
        form: "arabica_plantation",
        grade: "A",
      },
      evidence: [
        { field: "roasted", sourceText: "Roasted" },
        { field: "form", sourceText: "Arabica plantation" },
        { field: "grade", sourceText: "Grade A" },
        { field: "decaffeinated", sourceText: "non-decaffeinated" },
        { field: "presentation", sourceText: "bulk" },
      ],
      ambiguities: [],
    }

    const mockProvider = createMockCoffeeProvider(mockGeminiPayload)
    const extractionResult = await extractCoffeeDescription(sourceText, {
      provider: mockProvider,
    })

    // Gemini response contains ZERO HS codes
    expect((extractionResult.attributes as unknown as Record<string, unknown>).hsCode).toBeUndefined()
    expect((extractionResult.attributes as unknown as Record<string, unknown>).hsCode).toBeUndefined()
    expect((extractionResult as unknown as Record<string, unknown>).classification).toBeUndefined()

    // 2. User confirms extraction -> converted to CoffeeClassificationInput
    const conversion = toCoffeeClassificationInput(extractionResult.attributes)
    expect(conversion.success).toBe(true)
    if (!conversion.success) return

    // 3. UI passes facts to classifyCoffee()
    const classificationResult = classifyCoffee(conversion.input)

    // 4. Deterministic engine returns 0901 21 10
    expect(classificationResult.status).toBe("classified")
    if (classificationResult.status === "classified") {
      expect(classificationResult.hsCode).toBe("09012110")
      expect(classificationResult.hsCodeFormatted).toBe("0901 21 10")
      expect(classificationResult.matchedRuleId).toBe("COF-018")
      expect(classificationResult.structuredExplanation.productType).toBe("Coffee")
      expect(classificationResult.structuredExplanation.roastedState).toBe("Roasted")
      expect(classificationResult.structuredExplanation.decaffeinatedState).toBe("Non-decaffeinated")
      expect(classificationResult.structuredExplanation.presentation).toBe("Bulk packing")
    }
  })
})
